# Generated by Django 2.1.7 on 2020-12-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gec_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
